"""Add role field to users.

Revision ID: 0b4573ef35ae
Revises: c90eb34cc2e1
Create Date: 2025-02-09 01:11:46.270754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4573ef35ae'
down_revision: Union[str, None] = 'c90eb34cc2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
